# Generated by Django 3.2.4 on 2021-06-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_drink'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drink',
            table='drink',
        ),
    ]
