# Generated by Django 3.2.4 on 2021-06-18 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allergydrink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergydrink',
            old_name='Allergy',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergydrink',
            old_name='Drink',
            new_name='drink',
        ),
    ]
