# Generated by Django 3.2.4 on 2021-06-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
